<?php echo $this->doctype() . "\n"; ?>
<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zend Framework Tutorial');
?>

<html>
 <head>
<?php
$this->headLink()->appendStylesheet($this->basePath('/css/_styles.css'));
$this->headLink()->appendStylesheet($this->basePath('/css/menu.css'));
$this->headLink()->appendStylesheet($this->basePath('/css/bootstrap.css'));
//$this->headLink()->appendStylesheet('http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css');
?>

<style>
 body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }
</style>



<?php
echo $this->headMeta();
echo $this->headTitle();
echo $this->headStyle();
echo $this->headLink();
echo $this->headScript();
?>

  <?php /*
    if ($this->JQuery()->isEnabled())
    echo $this->JQuery()
    ->uiEnable()
    ->setLocalPath($this->basePath('/js/jquery/jquery.min.js'))
    ->setUiLocalPath($this->basePath('/js/jquery/jquery-ui.min.js'))
    ->addStylesheet('/js/jquery/jquery-ui-1.7.3.custom.css');
   */
  ?>


 </head>
 <body class="claro">
  <div id="page">
   <div id="header"> &nbsp;</div>


   <!--  <div id=navigation>
             <ul>
<?php
//echo $this->navigation('Navigation')->menu()->setPartial(array('partial/menu.phtml','default'))->setUlClass('nav');
//      echo $this->navigation('Navigation')->menu()->setPartial(array('partial/menu.phtml','default'));
?>
                                                         </ul>
                                                           </div>
   -->


<div>
<?php
//echo $this->navigation()->menu()->setPartial(array('menu.phtml', 'default'))->render();
echo $this->navigation('Navigation')->menu()->render();
?>
</div>

   <div id="wrap">

    <div id="content">
      <?php echo $this->layout()->content; ?>
    </div>



   </div>

  </div>


  <div id="footer">

   <div style="float:right; margin:0px 0px; font-family: Arial,Helvetica,sans-serif;font-size: 11px; text-decoration: none;">
    2010-2012 &copy;<a href="mailto:billing@telesystems.ua">&nbsp;ООО «Телесистемы Украины»</a>
   </div>



  </div>
 </body>
</html>